### ISSUE TITLE
screening failing without obvious reasons

### ISSUE THREAD

**Issue by dwr-psandhu** [CADWRDeltaModeling/dms_datastore#14]
Not all data in formatted makes it so screening. 

E.g. 
No matches found for pattern: *_bdt_b95740_temp_*.csv
File not found, format not supported or error during read: refactor_test/screened/*_bdt_b95740_temp_*.csv. Last reader tried = read_dms1
Can confirm found file(s) from pattern (false negative possible): False

However stage makes it but not velocity or temp.

**Comment by dwr-psandhu** [comment]
Might be related to issue #15 

E.g. carbq ec is having this problem which is also mentioned in issue #15 

`
Skipping *_c24_380318121571501_velocity_*.csv due to error
Caching 82 ::*_carqb_11455820_ec_*.csv
No matches found for pattern: *_carqb_11455820_ec_*.csv
File not found, format not supported or error during read: refactor_test/screened/*_carqb_11455820_ec_*.csv. Last reader tried = read_dms1
Can confirm found file(s) from pattern (false negative possible): False
`

**Comment by water-e** [comment]
Split inventory so expecations are consistent with contents
