### ISSUE TITLE
NSL temperature data incorrect units

### ISSUE THREAD

**Issue by dwr-psandhu** [CADWRDeltaModeling/dms_datastore#18]
NSL station is listed as deg_f but according to the download meta data it is in degree Celsius. Please correct

Also perhaps there should be a way to check station database against downloaded meta data to warn.

**Comment by dwr-psandhu** [comment]
Another example where this may be a case of topping off with CDEC which has different units than those of the source
See 
https://dwrbdodatastore.azurewebsites.net/repoui?sdate=2023-10-05T21%3A24&edate=2023-11-15T21%3A24&repo_level=%5B%27formatted%27%2C+%27screened%27%5D&selections=glc2%7C%7Ctemp
![glc2](https://github.com/CADWRDeltaModeling/dms_datastore/assets/11561317/e5e9e304-1dc4-4bbe-858a-5a0ad896633a)

**Comment by water-e** [comment]
I am unable to see the issue. In the formatted directory, I'm seeing cdec temperatures listed as deg F and other sources as deg C.  The data are separate, but individually I think they are OK. Maybe missing something?

By the time the data screened, units are supposed to be standardized. cdec is regarded as a provisional addition to ncro or des data and they are listed as the source with a small caveat in the metadata. There should no longer be any deg F in screened and at least tenatively I'm not seeing any. 

Other potential confusion is that there is nsl temperature Dave's gauge) and nsl2 (DISE/DES). Normally I would defer to the one that is not a flow station.

**Comment by dwr-psandhu** [comment]
The example for this was glc. The link broke because the continous_station_repo_beta does not have "formatted" subdir but "formatted_1yr". See the link below
https://dwrbdodatastore.azurewebsites.net/repoui?sdate=2023-10-05T21%3A24&edate=2023-11-15T21%3A24&repo_level=%5B%27formatted_1yr%27%2C+%27screened%27%5D&selections=glc2%7C%7Ctemp

**Comment by water-e** [comment]
Can you note what you did to access the data? For Formatted, it isn't clear why cdec would be grafted to ncro if you are using read_ts. Are you using read_ts_repo?

In screened (which I don't see here, not sure why) the two would be reconciled.

________________________________

**Comment by dwr-psandhu** [comment]
misunderstanding on how formatted works. Will only use screened data from now on
