### ISSUE TITLE
screening scripts need to be cleaned up and committed

### ISSUE THREAD

**Issue by dwr-psandhu** [CADWRDeltaModeling/dms_datastore#22]
Screening scripts are not in the repo. These need to be put under version control.

**Comment by water-e** [comment]
The screening scripts are now in the repo. auto_screen is a console (executable) script and the yaml configuration is in /config_data and it should be found there without intervention. Typical usage airlifted from auto_screen_tasks.bat is:

> auto_screen --config screen_config_v20230126 --fpath w:\continuous_station_repo_beta\formatted --dest screened --plot_dest plots --params elev
