### ISSUE TITLE
variables flag not respected for agency ncro

### ISSUE THREAD

**Issue by dwr-psandhu** [CADWRDeltaModeling/dms_datastore#30]
```
populate_repo --agencies ncro --variables flow --dest raw
```

results in all ~6000 data streams to be downloaded.

**Comment by water-e** [comment]
I'll see what I can do. You have a use case for this? 

At some point the cumulative issues with NCRO may motivate us to try to create a downloader based on web services.

**Comment by water-e** [comment]
Besides the fact that I don't have a use case for this, my concern here is that there are not a total of 6000 files in /raw for all the agencies, let alone NCRO. Should be 2000 across all the agencies in large time shards. Moreover, in my downloads NOAA is so dominant in its slowness (slightly USGS) that it would be the focus of any optimization.

**Comment by dwr-psandhu** [comment]
NOAA is fixed using the executor ( i followed your pattern). 
For NCRO it is not possible as it does all variables no matter what is specified.

**Comment by water-e** [comment]
Ready for testing
