### ISSUE TITLE
cdec multiprocessing vs single processing version of download

### ISSUE THREAD

**Issue by water-e** [CADWRDeltaModeling/dms_datastore#33]
It seems like for cdec the downloads were done twice, one single proc and one multiproc. 

I have commmitted code that gets rid of the redundant multiprocessing version. I pruned that one snce there is also a thread/proc safety issue that I raised as a different issue. 

That is just a hack though. The multiprocessing would be easy to reinstate -- I left it as commented out.

**Comment by dwr-psandhu** [comment]
Based on discussion yesterday, this may not be an issue ? Closing.
