### ISSUE TITLE
Use logging instead of print to manage verbosity of messages

### ISSUE THREAD

**Issue by dwr-psandhu** [CADWRDeltaModeling/dms_datastore#4]
* dms_datastore version: 29e5396
* Python version: 3.7
* Operating System: Linux

### Description

Logging can be a drop in replacement for print. Furthermore logging can be done to both console and file with different levels of logging so that more detailed logs can exist in file than on console

**Comment by dwr-psandhu** [comment]
Moved as gently as I could to logging. Some messages are coming from other modules that are outside so will close this issue for now.

**Comment by kjnam** [comment]
Agreed.
