### ISSUE TITLE
`infer_datetime_format` warning from `csv_retrieve_ts`

### ISSUE THREAD

**Issue by kjnam** [CADWRDeltaModeling/dms_datastore#5]
* schimpy version: [#29e5396](https://github.com/CADWRDeltaModeling/dms_datastore/commit/29e5396fdffa0a3375453c01f258f79db2785db3)
* Operating System: Linux

Reported on behalf of Hans

### Description
Every time csv_retrieve_ts from dms_datastore. read_ts is run, we get the following warning message:

```
dms_datastore/dms_datastore/read_ts.py:972: FutureWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see...
```

**Comment by kjnam** [comment]
This is a warning from Pandas Version 2. See https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html.
The argument is removed by https://github.com/CADWRDeltaModeling/dms_datastore/commit/b54c2599dd803db5b4379664cc0b9743431eea35.

**Comment by HansKimDWR** [comment]
Great! Thank you!
