### ISSUE TITLE
multiple failures with latest update repo

### ISSUE THREAD

**Issue by dwr-psandhu** [CADWRDeltaModeling/dms_datastore#54]
### Description
version: dms-datastore             0.4.2+15.g1f02368   

Running usual jenkins update after updating to latest dms_datastore version and there were multiple errors with an example below during the reformat part of the pipeline

```
Exception args: 
 ('`np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.',)
Could not read file: raw\ncro_glab_b9531000_ph_2006_2013.csv```

**Comment by water-e** [comment]
In testing.
