### ISSUE TITLE
Fix HRRR base_date and units

### ISSUE THREAD

**Issue by water-e** [CADWRDeltaModeling/dms_datastore#57]
Base date should be a tuple of ints and units should be in days. 

The original code was OK but got units of time[:] changed to hours in May 2024 so this is a regression issue. Comparing to a previous download (say April 1 2024) would be an acceptable test. It would be good to test within schism using wind speed and comparing to a known station.

This bug has the potential to "silently succeed but be wrong".

There is a data component: archived files in Modeling_Data and on hpc5 will have to be overwritten.

**Comment by qiangshu** [comment]
HRRR time has been reverted to unit of days, base date is tuple of Ints. I saw Modeling_data is updated continuously, but not hpc5.
